version: '3.1'
services:
  naumen-mysqldb:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "/data/sql:/var/www/html"
    ports:
      - "3333:3306"
    environment:
      MYSQL_DATABASE: "naumen"
      MYSQL_ROOT_PASSWORD: "qwer1234"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"


  naumen-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - naumen-mysqldb
    environment:
      PMA_HOST: naumen-mysqldb
      PMA_PORT: 3306
    ports:
      - '2020:80'